version: '3'

services:

  redis:
    image: redis:5.0.5
    ports: 
      - 6379

  stocktopus:
    image: quay.io/thorfour/stocktopus
    links:
      - redis
    command:
      - "/server"
      - "-p=8080"
      - "-n"
    ports:
      - 8080
    environment:
      REDISADDR: "redis:6379"
      IEX_API_TOKEN: ${IEX_API_TOKEN}

  e2e-tests:
    image: golang:1.12.1
    links:
      - stocktopus
    working_dir: ${PWD}
    volumes:
      - ./e2e:${PWD}/e2e
    entrypoint: "go test -v -tags e2e ./..."
